project_id = "vnuvhreveoyclasgtnpr"

[functions.scrape-leads]
verify_jwt = false

[functions.process-order]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false